name: "ciaopet"
version: "3.7"

services:
  app:
    depends_on:
      - db
    build:
      args:
        user: ciaopet
        uid: 1000
      context: ./
      dockerfile: .docker/php8.4-fpm.dockerfile
    image: ciaopet/app
    container_name: ciaopet-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    command:
      sh -c "composer install --ignore-platform-reqs \
        && php artisan key:generate \
        && npm install \
        && npm run build \
        && php artisan migrate --force \
        && php artisan db:seed --force \
        && docker-php-entrypoint php-fpm"
    networks:
      - ciaopet
  db:
    image: mysql:8.0
    container_name: ciaopet-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 33068:3306
    volumes:
      - .docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - ciaopet
  nginx:
    image: nginx:1.17-alpine
    container_name: ciaopet-nginx
    restart: unless-stopped
    ports:
      - 8098:80
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      - ciaopet

networks:
  ciaopet:
    driver: bridge
    external: false